on:
    pull_request:
        types: opened

jobs:
    first_time_contributor:
        runs-on: ubuntu-latest
        if: contains(github.event.pull_request.title, 'first')
        steps:
            - run: |
                PR_COMMENT="Congratulations on your first PR!"
                curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d "{\"body\":\"$PR_COMMENT\"}" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
            
                